name: 'TagCommit'
description: 'Tags the commit with the version number'

runs: 
  using: composite
  steps:
    - name: Tag Commit
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}      
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        $tag = "v${{ steps.setup.outputs.GitVersion_FullSemVer }}"
        git tag $tag
        git push origin $tag