name: Main

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          lfs: true
          submodules: recursive
          fetch-depth: 0

      - id: setup
        uses: ./steps/setup
        with:
          dotnet: 'false'

      - uses: ./steps/git/tag-commit
        with:
          version: ${{ steps.setup.outputs.GitVersion_FullSemVer }}
